######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 27 17:20:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Sudoku_Solver.h
SOURCES += main.cpp Sudoku_Solver.cpp
RESOURCES += Sudoku_Solver_1.1_NoGrid.qrc
